application: observingreports
version: 0-1
runtime: python
api_version: 1

handlers:
- url: /ext
  static_dir: ext-4.0.2

- url: /js
  static_dir: js

- url: /.*
  script: observingreports.py
  login: required

builtins:
- datastore_admin: on
